import assert from "node:assert/strict";
import { test } from "node:test";

import { autogeneratedComment } from "../src/helpers/autogenerated-comment.mjs";

test("autogeneratedComment builds the banner from the worker name", function () {
  assert.equal(
    autogeneratedComment("css"),
    "// AUTOGENERATED by jarmuz/worker-css.\n" +
      "// Do not edit this file directly.\n" +
      "// It will be overwritten on the next build.",
  );
});
