import assert from "node:assert/strict";
import { test } from "node:test";

import { autogeneratedComment } from "../src/helpers/autogenerated-comment.mjs";

test("autogeneratedComment embeds the worker name in the banner", function () {
  assert.ok(autogeneratedComment("stylesheet").includes("stylesheet"));
});
