import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { test } from "node:test";

import { makeTempDirectory } from "./support/temp-directory.mjs";
import { runWorkerBuild } from "./support/run-worker-build.mjs";

test("basic passes context helpers into the build function", async function () {
  const tempDirectory = await makeTempDirectory();
  const resultFile = join(tempDirectory.path, "result.txt");

  const message = await runWorkerBuild(
    "worker-basic-uses-context-helpers",
    {
      baseDirectory: tempDirectory.path,
      buildId: "build-1",
      name: "stylesheet",
    },
    { env: { ...process.env, JARMUZ_RESULT_FILE: resultFile } },
  );

  assert.equal(message.success, true);
  assert.equal(
    await readFile(resultFile, "utf8"),
    "// AUTOGENERATED by jarmuz/worker-stylesheet.\n" +
      "// Do not edit this file directly.\n" +
      "// It will be overwritten on the next build.",
  );

  await tempDirectory.cleanup();
});
