import { autogeneratedComment } from "../helpers/autogenerated-comment.mjs";
import { printSubtreeList } from "../helpers/print-subtree-list.mjs";
import { resetConsole } from "../helpers/reset-console.mjs";
import { sleep } from "../helpers/sleep.mjs";
import { workerPort } from "../libs/worker-port.mjs";

/**
 * @typedef {object} BasicContext
 * @property {string} autogeneratedComment
 * @property {string} baseDirectory
 * @property {string} buildId
 * @property {string} name
 * @property {(input: import("../helpers/format-subtree-list.mjs").SubtreeList) => void} printSubtreeList
 * @property {() => void} resetConsole
 * @property {(options: { delay: number }) => Promise<void>} sleep
 */

/**
 * @param {(context: BasicContext) => unknown} build
 */
export function basic(build) {
  const port = workerPort();

  port.onMessage(async function (message) {
    const { baseDirectory, buildId, name } = message;

    /** @param {boolean} success */
    function reportBuildResult(success) {
      port.postBuildResult({
        baseDirectory,
        buildId,
        success,
      });
    }

    try {
      reportBuildResult(
        false !==
          (await build({
            autogeneratedComment: autogeneratedComment(name),
            buildId,
            baseDirectory,
            name,
            printSubtreeList,
            resetConsole,
            sleep,
          })),
      );
    } catch (error) {
      console.error(
        `Build ${buildId} failed because of uncaught exception:`,
        error,
      );

      reportBuildResult(false);
    }
  });
}
