import { parentPort } from "node:worker_threads";

import { autogeneratedComment } from "../helpers/autogenerated-comment.mjs";
import { printSubtreeList } from "../helpers/print-subtree-list.mjs";
import { resetConsole } from "../helpers/reset-console.mjs";
import { vimgrep } from "../helpers/vimgrep.mjs";

export function basic(build) {
  parentPort.on("message", async function ({ baseDirectory, buildId, name }) {
    function reportSuccess(success) {
      parentPort.postMessage({
        baseDirectory,
        buildId,
        success,
      });
    }

    try {
      reportSuccess(
        false !==
          (await build({
            autogeneratedComment: autogeneratedComment(name),
            buildId,
            baseDirectory,
            name,
            printSubtreeList,
            resetConsole,
            vimgrep,
          })),
      );
    } catch (error) {
      console.error(
        `Build ${buildId} failed because of uncaught exception:`,
        error,
      );

      reportSuccess(false);
    }
  });
}
