import assert from "node:assert/strict";
import { parentPort } from "node:worker_threads";

import { autogeneratedComment } from "../helpers/autogenerated-comment.mjs";
import { printSubtreeList } from "../helpers/print-subtree-list.mjs";
import { resetConsole } from "../helpers/reset-console.mjs";
import { sleep } from "../helpers/sleep.mjs";

/**
 * @typedef {object} BasicContext
 * @property {string} autogeneratedComment
 * @property {string} baseDirectory
 * @property {string} buildId
 * @property {string} name
 * @property {(input: import("../helpers/format-subtree-list.mjs").SubtreeList) => void} printSubtreeList
 * @property {() => void} resetConsole
 * @property {(options: { delay: number }) => Promise<void>} sleep
 */

/**
 * @param {(context: BasicContext) => unknown} build
 */
export function basic(build) {
  assert(parentPort, "basic() must run in a worker thread");

  const port = parentPort;

  port.on(
    "message",
    /** @param {import("../libs/keep-worker-alive.mjs").BuildMessage} message */
    async function (message) {
      const { baseDirectory, buildId, name } = message;

      /** @param {boolean} success */
      function reportSuccess(success) {
        port.postMessage({
          baseDirectory,
          buildId,
          success,
        });
      }

      try {
        reportSuccess(
          false !==
            (await build({
              autogeneratedComment: autogeneratedComment(name),
              buildId,
              baseDirectory,
              name,
              printSubtreeList,
              resetConsole,
              sleep,
            })),
        );
      } catch (error) {
        console.error(
          `Build ${buildId} failed because of uncaught exception:`,
          error,
        );

        reportSuccess(false);
      }
    },
  );
}
